### ISSUE TITLE
eth_utils.address: fails on pypy 7.1

### ISSUE THREAD

**Issue by oberstet** [ethereum/eth-utils#173]
I am trying to get an app that (indirectly) uses eth-utils and which runs fine on CPython to run on PyPy.

I've narrowed down the issue I seem to run into down to the following difference in behavior on CPython and PyPy .. I haven't identified the root cause / code though. Anything I might try?

Test program:

```python
import os
import eth_keys
import web3

seller_key = os.urandom(32)
print(seller_key)

pkey = eth_keys.keys.PrivateKey(seller_key)
print(pkey.__class__, dir(pkey))

addr = pkey.public_key.to_canonical_address()
print(addr)

caddr = web3.Web3.toChecksumAddress(addr)
print(caddr)
```

When run on CPython (success):

```console
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/dsq-examples/examples/python$ python
Python 3.7.4 (default, Sep 27 2019, 08:30:36) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import eth_keys
>>> import web3
>>> 
>>> seller_key = os.urandom(32)
>>> print(seller_key)
b'\xb79\xb4\xaf\xf9\xa6\x8d\x84\x88v\xedM$I\xf0(\x96\x0b\x83"!\x01\xde\xed\x84\xd6\xb5\x06\x95\r\xcb\xa9'
>>> 
>>> pkey = eth_keys.keys.PrivateKey(seller_key)
>>> print(pkey.__class__, dir(pkey))
<class 'eth_keys.datatypes.PrivateKey'> ['__abstractmethods__', '__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__hex__', '__index__', '__init__', '__init_subclass__', '__int__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_backend', '_raw_key', 'backend', 'count', 'get_backend', 'index', 'public_key', 'sign_msg', 'sign_msg_hash', 'sign_msg_hash_non_recoverable', 'sign_msg_non_recoverable', 'to_bytes', 'to_hex']
>>> 
>>> addr = pkey.public_key.to_canonical_address()
>>> print(addr)
b'\x13\x95\x0f0\xba\xdb\xc8"\x07@\xf2i\xcd}\xca\xb5\xb4\xcf\xb7A'
>>> 
>>> caddr = web3.Web3.toChecksumAddress(addr)
>>> print(caddr)
0x13950f30badbc8220740F269Cd7DcAb5b4cfB741
>>> 
```

When run on PyPy (failed):

```console
(pypy3_1) oberstet@intel-nuci7:~/scm/crossbario/dsq-examples/examples/python$ python
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``we are moving towards a really
patch-free assembler world (armin)''
>>>> import os
>>>> import eth_keys
>>>> import web3
>>>> 
>>>> seller_key = os.urandom(32)
>>>> print(seller_key)
b'\xd8\xb2v\x02\x0b?=R\xb1\x8bo\xc7\xf7aU:e \xcb\xefW\xbd\r*E\x03h\xe8\x96\xee\xc2\xc5'
>>>> 
>>>> pkey = eth_keys.keys.PrivateKey(seller_key)
>>>> print(pkey.__class__, dir(pkey))
<class 'eth_keys.datatypes.PrivateKey'> ['__abstractmethods__', '__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__hex__', '__index__', '__init__', '__init_subclass__', '__int__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_backend', '_raw_key', 'backend', 'count', 'get_backend', 'index', 'public_key', 'sign_msg', 'sign_msg_hash', 'sign_msg_hash_non_recoverable', 'sign_msg_non_recoverable', 'to_bytes', 'to_hex']
>>>> 
>>>> addr = pkey.public_key.to_canonical_address()
>>>> print(addr)
b'\t\xbc@\x06\xc5\x14\x18\x87EmY?\x02`1\x1f\x88\xc9\xc8\xcb'
>>>> 
>>>> caddr = web3.Web3.toChecksumAddress(addr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oberstet/pypy3_1/site-packages/eth_utils/address.py", line 109, in to_checksum_address
    norm_address = to_normalized_address(value)
  File "/home/oberstet/pypy3_1/site-packages/eth_utils/address.py", line 64, in to_normalized_address
    "Unknown format {}, attempted to normalize to {}".format(value, hex_address)
ValueError: Unknown format b'\t\xbc@\x06\xc5\x14\x18\x87EmY?\x02`1\x1f\x88\xc9\xc8\xcb', attempted to normalize to 0x09bc4006c5141887456d593f0260311f88c9c8cb
>>>> print(caddr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'caddr' is not defined
>>>> 
```

**Comment by pipermerriam** [comment]
What version of `pypy` are you running.

**Comment by pipermerriam** [comment]
Nevermind, I see it in the code block you dumped.

Looking at our CI runs which do test against `pypy` it looks like we're testing against `7.0.0`. 

https://circleci.com/gh/ethereum/eth-utils/1851

Your version appears to be newer (and in beta).

**Comment by oberstet** [comment]
Yes, you're right! Thanks for pointing that out=)

I retested with both versions of PyPy for both above code snipped and the actual code I'm working on. Results are:

**It succeeds on**:

```
(pypy35_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python/examples/xbr$ python -V
Python 3.5.3 (928a4f70d3de, Feb 08 2019, 10:42:58)
[PyPy 7.0.0 with GCC 6.2.0 20160901]
```

**and fails on**:

```
(pypy3_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python/examples/xbr$ python -V
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901]
```

---

In summary, PyPy 7.0 is fine! The current beta PyPy 7.1 runs into this issue.

**Comment by pipermerriam** [comment]
Ok, with that said, I'm still curious to understand why this is failing.  It seems `is_address` is returning `False` (where it should return `True`).  That implies one of `is_hex_address`, `is_binary_address` or `is_checksum_formatted_address` is mis-behaving, returning `False` when it should return `True`.  Based on your code example it looks like `is_binary_address` is probably the offender.  Can you check whether `eth_utils.is_binary_address(b'\x13\x95\x0f0\xba\xdb\xc8"\x07@\xf2i\xcd}\xca\xb5\xb4\xcf\xb7A')` returns `True` or `False`?

**Comment by oberstet** [comment]
mmh, not sure, that seems to return the same on both pypy versions:

```(pypy3_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python/examples/xbr$ python
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``http://twitpic.com/52ae8f''
>>>> import eth_utils
>>>> eth_utils.is_binary_address(b'\x13\x95\x0f0\xba\xdb\xc8"\x07@\xf2i\xcd}\xca\xb5\xb4\xcf\xb7A')
True
>>>> 
```

and

```
(pypy35_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python/examples/xbr$ python
Python 3.5.3 (928a4f70d3de, Feb 08 2019, 10:42:58)
[PyPy 7.0.0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import eth_utils
>>>> eth_utils.is_binary_address(b'\x13\x95\x0f0\xba\xdb\xc8"\x07@\xf2i\xcd}\xca\xb5\xb4\xcf\xb7A')
True
>>>> 
```

**Comment by pipermerriam** [comment]
problem appears to be with the `is_hex` check.  This specifically is the offending line:

```python
>>>> codecs.decode('13950f30badbc8220740f269cd7dcab5b4cfb741', 'hex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'hex' decoder returned 'bytes' instead of 'str'; use codecs.decode() to decode to arbitrary types
```

In CPython and the previous version of `pypy` this line returns a bytestring.

**Comment by oberstet** [comment]
oh yes! seems to be an issue in pypy-7.1 .. as in:

```
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx/docker$ source ~/pypy3_1/bin/activate
(pypy3_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx/docker$ python
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``JIT compilers should be written
by people who actually have faith in JIT compilers' ability to makes things go
screaming fast''
>>>> import codecs
>>>> codecs.decode('13950f30badbc8220740f269cd7dcab5b4cfb741', 'hex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'hex' decoder returned 'bytes' instead of 'str'; use codecs.decode() to decode to arbitrary types
>>>> 
(pypy3_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx/docker$ source ~/pypy35_1/bin/activate
(pypy35_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx/docker$ python
Python 3.5.3 (928a4f70d3de, Feb 08 2019, 10:42:58)
[PyPy 7.0.0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import codecs
>>>> codecs.decode('13950f30badbc8220740f269cd7dcab5b4cfb741', 'hex')
b'\x13\x95\x0f0\xba\xdb\xc8"\x07@\xf2i\xcd}\xca\xb5\xb4\xcf\xb7A'
>>>> 
```
