### ISSUE TITLE
ImportError when importing pad_left and pad_right from eth_utils

### ISSUE THREAD

**Issue by jacobAtAnalytixBar** [ethereum/eth-utils#73]
* Version: Latest
* Python: 3.5
* OS: osx/linux

### What was wrong?

Code:
**from eth_utils import (
            pad_left,
            pad_right,
        )**

Error message:
**"Exception Value: | cannot import name 'pad_left'"**

### How can it be fixed?

It looks like in the more recent version of eth_utils, there is no longer a file called "formatting.py" which contains the function defs for pad_left() and pad_right() functions.  There is also no longer an import for these in the __init__.py in the root "eth_utils" folder.

I have a docker setup which is installing fresh from pip each deployment so it would be nice if this was fixed.  The import for pad_left and pad_right is actually called from the "eth_abi" library, not my custom code.  The location it is called in eth_abi is:  eth_abi/utils/padding.py

Thank you!

**Comment by carver** [comment]
> Version: Latest

Can you be more specific?

**Comment by jacobAtAnalytixBar** [comment]
Yes sorry - here is the version as returned by "pip list":  eth-utils (1.0.0b2)

**Comment by carver** [comment]
Can you post the full `pip freeze`? Updating to the latest version of web3.py fixes these issues AFAIK.

**Comment by jacobAtAnalytixBar** [comment]
You're right.  I was using older version of Web3 - moreover I was using Piper's version which was last updated in November.  My apologies and thanks for your quick replies.

**Comment by rakanalh** [comment]
I also see this issue when i try to run web3's tests.

I have web3 and eth-utils installed manually based on their latest master branches.

```
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/_pytest/config.py", line 329, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/rakan/Code/Ethereum/web3.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/_pytest/config.py", line 360, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/rakan/Code/Ethereum/web3.py/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/rakan/Code/Ethereum/web3.py/conftest.py", line 4, in <module>
    from web3.providers.eth_tester import (
  File "/home/rakan/Code/Ethereum/web3.py/web3/providers/eth_tester/__init__.py", line 2, in <module>
    from .main import (  # noqa: F401
  File "/home/rakan/Code/Ethereum/web3.py/web3/providers/eth_tester/main.py", line 10, in <module>
    from eth_tester import (
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/eth_tester/__init__.py", line 5, in <module>
    from .main import (  # noqa: F401
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/eth_tester/main.py", line 35, in <module>
    from eth_tester.backends import (
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/eth_tester/backends/__init__.py", line 11, in <module>
    from .mock import (  # noqa: F401
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/eth_tester/backends/mock/__init__.py", line 1, in <module>
    from .main import (  # noqa: F401
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/eth_tester/backends/mock/main.py", line 32, in <module>
    from eth_tester.utils.accounts import (
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/eth_tester/utils/accounts.py", line 8, in <module>
    from .secp256k1 import (
  File "/home/rakan/.pyenv/versions/3.6.0/envs/web3test/lib/python3.6/site-packages/eth_tester/utils/secp256k1.py", line 4, in <module>
    from eth_utils import (
ImportError: cannot import name 'pad_left'
ERROR: could not load /home/rakan/Code/Ethereum/web3.py/conftest.py
```

pip freeze shows:
```
apipkg==1.4
argh==0.26.2
attrdict==2.0.0
attrs==17.4.0
bitcoin==1.1.42
bumpversion==0.5.3
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.3.9
coverage==4.5.1
cytoolz==0.9.0.1
decorator==4.2.1
docopt==0.6.2
eth-abi==1.0.0
eth-account==0.1.0a2
eth-hash==0.1.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.0
eth-tester==0.1.0b11
eth-testrpc==1.3.3
-e git+git@github.com:ethereum/eth-utils.git@5eb14e3eb31dd2e88ab911da064e120932feb0cc#egg=eth_utils
ethereum==1.6.1
execnet==1.5.0
flake8==3.5.0
flaky==3.4.0
hexbytes==0.1.0
hypothesis==3.49.0
idna==2.6
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.1
json-rpc==1.10.8
lru-dict==1.1.6
mccabe==0.6.1
parso==0.1.1
pathtools==0.1.2
pbkdf2==1.3
pexpect==4.4.0
pickleshare==0.7.4
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.2
py-solc==2.1.0
pycodestyle==2.3.1
pycparser==2.18
pycryptodome==3.5.0
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.2.0
pysha3==1.0.2
pytest==3.4.2
pytest-forked==0.2
pytest-mock==1.7.1
pytest-pythonpath==0.7.2
pytest-watch==4.1.0
pytest-xdist==1.22.2
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
secp256k1==0.13.2
semantic-version==2.6.0
simplegeneric==0.8.1
six==1.11.0
toolz==0.9.0
tox==2.9.1
tqdm==4.19.7
traitlets==4.3.2
urllib3==1.22
virtualenv==15.1.0
watchdog==0.8.3
wcwidth==0.1.7
-e git+git@github.com:rakanalh/web3.py.git@c7f4137bc05dbfadad02371d530637b5ae0d5e37#egg=web3
Werkzeug==0.14.1
```

**Comment by pipermerriam** [comment]
`pad_left` and `pad_right` were removed from web3.py.  You likely need to update your web3.py to the latest master or downgrade `eth-utils` to a pre `1.0` version.

**Comment by pipermerriam** [comment]
Actually, it looks like you need to upgrade your `eth-tester` version.
