### ISSUE TITLE
Ubuntu-16.04 cannot run populus and error message is "ImportError: cannot import name 'force_text'"

### ISSUE THREAD

**Issue by santai87** [ethereum/eth-utils#81]
* Version: 2.2.0
* Python: 3.5.2
* OS: linux
* eth_utils: 1.0.1

### Problem Description

1. Use pip install populus
`pip install populus`

2. Type this command

`populus compile`

3. Show error message
```
Traceback (most recent call last):
  File "/home/manager/Github_Project/ICO_contracts/venv_3/bin/populus", line 7, in <module>
    from populus.cli import main
  File "/home/manager/Github_Project/ICO_contracts/venv_3/lib/python3.5/site-packages/populus/__init__.py", line 24, in <module>
    from .project import Project  # NOQA
  File "/home/manager/Github_Project/ICO_contracts/venv_3/lib/python3.5/site-packages/populus/project.py", line 10, in <module>
    from populus.config.defaults import (
  File "/home/manager/Github_Project/ICO_contracts/venv_3/lib/python3.5/site-packages/populus/config/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/home/manager/Github_Project/ICO_contracts/venv_3/lib/python3.5/site-packages/populus/config/base.py", line 12, in <module>
    from populus.utils.mappings import (
  File "/home/manager/Github_Project/ICO_contracts/venv_3/lib/python3.5/site-packages/populus/utils/mappings.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'
```

### How can it be fixed?

Probably the new version of eth-utils has no function named 'force_text' and populus uses it.

Need a method that can compile populus from source code

**Comment by santai87** [comment]
Try `pip install --upgrade web3`

**Comment by Netherdrake** [comment]
Ran into the same issue, @santai87's answer worked as a quick "fix".

**Comment by Netherdrake** [comment]
This issue is still thorny, and unfortunately in some situations `pip install -U web3` won't do.
https://github.com/ethereum/eth-keys/issues/39

**Comment by reedsa** [comment]
Closing this inactive thread, please open a new issue if you experience any further problems.
